# Generated by Django 4.2.27 on 2026-02-16 10:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default=accounts.models.generate_reset_token, editable=False, max_length=32, unique=True),
        ),
    ]
