"""
Django settings for meditrack project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Always load local project env vars, even when started outside project root.
load_dotenv(BASE_DIR / ".env")


def _env(name: str) -> str:
    return (os.getenv(name) or "").strip().strip('"').strip("'")


DEBUG = True

SECRET_KEY = _env("SECRET_KEY") or "django-insecure-dev-only-secret-key"

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]

SITE_URL = "http://127.0.0.1:8000"


SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "APP": {
            "client_id": _env("GOOGLE_OAUTH_CLIENT_ID"),
            "secret": _env("GOOGLE_OAUTH_CLIENT_SECRET"),
        },
    }
}


INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "hospital",
    "accounts",
    "medi_rag",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "meditrack.middleware.SplitSessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "meditrack.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "meditrack.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": _env("DB_ENGINE") or "django.db.backends.postgresql",
        "NAME": _env("DB_NAME") or "meditrack",
        "USER": _env("DB_USER") or "postgres",
        "PASSWORD": _env("DB_PASSWORD") or "rms123",
        "HOST": _env("DB_HOST") or "localhost",
        "PORT": _env("DB_PORT") or "5432",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

SITE_ID = 1

LOGIN_URL = "accounts:login"
LOGOUT_URL = "accounts:logout"
LOGIN_REDIRECT_URL = "hospital:home"
LOGOUT_REDIRECT_URL = "hospital:landing_page"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

AUTH_USER_MODEL = "accounts.CustomUser"

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"
SOCIALACCOUNT_ADAPTER = "accounts.social_adapter.MeditrackSocialAccountAdapter"
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_LOGIN_ON_GET = True

SILENCED_SYSTEM_CHECKS = ["admin.E410"]

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = False
APP_SESSION_COOKIE_NAME = "app_sessionid"
APP_SESSION_COOKIE_PATH = "/"
ADMIN_SESSION_COOKIE_NAME = "admin_sessionid"
ADMIN_SESSION_COOKIE_PATH = "/admin/"

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

EMAIL_BACKEND = _env("EMAIL_BACKEND") or (
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = _env("EMAIL_HOST") or "smtp.gmail.com"
EMAIL_PORT = int(_env("EMAIL_PORT") or "587")
EMAIL_HOST_USER = _env("EMAIL_HOST_USER") or _env("DEFAULT_FROM_EMAIL")
EMAIL_HOST_PASSWORD = _env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = (_env("EMAIL_USE_TLS") or "true").lower() in {"1", "true", "yes", "on"}
DEFAULT_FROM_EMAIL = _env("DEFAULT_FROM_EMAIL") or "no-reply@localhost"
